version: "3.8"
services:
  pharmacy-recommendation-redis:
    container_name: pharmacy-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: congsole/pharmacy-recommendation-redis
    ports:
      - "6379:6379"
  pharmacy-recommendation-database:
    container_name: pharmacy-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: congsole/pharmacy-recommendation-database
    environment:
      - MARIADB_DATABASE=pharmacy-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "6000:3306"  # 접근 포트 설정 (컨테이너 외부 : 컨테이너 내부)
    #컨테이너 외부에서 사용할 포트는 application.yaml 파일의 데이터소스 유알엘과 일치시킴
    #컨테이너 외부에서 사용할 포트는 로컬의 마리아디비와 포트번호가 달라야함
    #나는 마이에스큐엘 3306, 마리아디비 4000으로 설정했기 때문에 또다른 6000으로 해줌.
